### ISSUE TITLE
Adds customer service button.

### ISSUE THREAD

**Issue by warrenrhodes** [karibu-cap/trans_all_client#38]
Sometimes, payment may be successful but the transfer may not go through due to unavailability of the device used for the transaction. While we have a schedule that informs us of any pending transactions, it's equally important for customers to quickly contact us in case of any issues with the application.

**Comment by RudyAzcuy** [comment]
I agree. I have been waiting for almost a month for a response to the account issues that we are having with Github

Request Received (#2306885)
