### ISSUE TITLE
Customer Service with GitHub is a huge problem.

### ISSUE THREAD

**Issue by RudyAzcuy** [karibu-cap/trans_all_client#48]
Request Received Ticket (#2306885)

I have been waiting for almost a month for a response that actually tries to address the reported account accessing issue. I continue to get messages like the following but no answers. Tell me how getting a response like this helps me? 

"We have not forgotten about you. We’ve been experiencing a high volume of tickets, driven by a greater than expected growth in customers. We have concrete plans to return to the responsive standard we are known for. Trust that your ticket is still in our queue and we’ll get you an answer as quickly as we can.
Thank you again for your understanding and patience.
The GitHub Team"

**Comment by Tadjaur** [comment]
@RudyAzcuy This project does not relate to your issue.
For any GitHub issue please contact the support [here](https://support.github.com/request).
